In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('logs_SPEDIA.csv')

In [3]:
data.head()

,Agent_name,User,Timestamp,Decoder_name,Description,Full_log,Content,Url,To,Cc,...,Attachments,Size,Size_before,Size_after,Filename,Path,Command,Level,Activity,Action
0,host-accesible_simulation,camilo,2025-03-06 13:15:10.797,auditd,Audit: Midly Suspicious Command executed: /bin...,type=SYSCALL msg=audit(1741266907.761:34184): ...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,systemctl,8.0,command,Command executed
1,servidor-interno_simulation,humberto,2025-03-06 13:14:35.211,pam,PAM: Login session opened.,Mar 6 14:14:32 servidor-interno systemd: pam_...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,session,Login
2,host-accesible_simulation,irene,2025-03-06 13:23:50.000,cert,NaN,NaN,from relief could arthur dont personal impress...,NaN,Sasha.Britanney.Quinn@dtaa.com,Sonya.Samantha.Hahn@dtaa.com;Josephine.Indira....,...,2.0,25593.0,NaN,NaN,NaN,NaN,NaN,NaN,email,Email sent
3,host-accesible_simulation,camilo,2025-03-06 13:21:47.000,cert,NaN,NaN,janet dissection since well villain his for ir...,http://walmart.com/The_Temple_at_Thatch/unacad...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http,URL accedida
4,host-accesible_simulation,camilo,2025-03-06 13:21:50.000,cert,NaN,NaN,peter country his occupy numbers brother colle...,http://cox.com/T26/tmm/pnzcvatpurpxyvfgfnyrfpb...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http,URL accedida

In [4]:
data.shape

(72250, 22)

In [5]:
data.drop(columns=['Url','Size','Size_before','Size_after','Filename','Path','Cc','Bcc'],inplace=True)

In [6]:
# Count all unique values in the 'Description' column
print(data['Description'].value_counts())

Description
Audit: Highly Suspicious Command executed: /bin/nc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            3279
Integrity checksum changed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   3132
PAM: Login session opened.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    3031
PAM: Login session closed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2038
Audit: Lowly Suspicious Command executed: /usr/bin/head                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1888
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...
El usuario ubuntu en el ordenador ubuntu-VirtualBox a accedido a la URL: https://mail.google.com/mail/u/0/#inbox/FMfcgzQXKDgZwXxfdtdWXvFmlHSvQNPB.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
El usuario ubuntu en el ordenador ubuntu-VirtualBox a accedido a la URL: https://www.base64decode.net/.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
El usuario ubuntu en el ordenador ubuntu-VirtualBox a accedido a la URL: https://docs.github.com/es/authentication/troubleshooting-ssh/recovering-your-ssh-key-passphrase.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
El usuario ubuntu en el ordenador ubuntu-VirtualBox a accedido a la URL: http://10.12.128.2:8080/.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
El usuario ubuntu en el ordenador ubuntu-VirtualBox a accedido a la URL: https://www.google.com/search?q=olaya+bolaya331499%40gmail.com+musica&client=ubuntu-sn&hs=rAH&sca_esv=ef113eae1f4c563c&channel=fs&biw=1076&bih=788&sxsrf=AHTn8zpiRGscKZNokFrOU4hO5ZOQ-lmRAQ%3A1743337750006&ei=FjnpZ-oO_Ins1g_JwIKIDQ&ved=0ahUKEwjq8b-a57GMAxX8BNsEHUmgANEQ4dUDCBA&uact=5&oq=olaya+bolaya331499%40gmail.com+musica&gs_lp=Egxnd3Mtd2l6LXNlcnAiI29sYXlhIGJvbGF5YTMzMTQ5OUBnbWFpbC5jb20gbXVzaWNhMgQQIRgVSPEQUGdY6Q5wAXgAkAECmAHXA6ABgw2qAQkwLjMuMy4wLjG4AQPIAQD4AQGYAgagAvsHwgIHECMYsAMYJ8ICCBAAGLADGO8FwgIFEAAY7wXCAggQABiABBiiBJgDAIgGAZAGBpIHBTEuMy4yoAeADw&sclient=gws-wiz-serp.       1
Name: count, Length: 390, dtype: int64

In [7]:
# Keep only rows with the specified Description values
filtered_data = data[data['Description'].isin([
    'Audit: Highly Suspicious Command executed: /bin/nc',
    'Audit: Lowly Suspicious Command executed: /usr/bin/head'
])]
filtered_data.reset_index(drop=True, inplace=True)
filtered_data.head()

,Agent_name,User,Timestamp,Decoder_name,Description,Full_log,Content,To,From,Attachments,Command,Level,Activity,Action
0,host-accesible_simulation,camilo,2025-03-06 13:44:07.090,auditd,Audit: Lowly Suspicious Command executed: /usr...,type=SYSCALL msg=audit(1741268643.921:34295): ...,NaN,NaN,NaN,NaN,head,5.0,command,Command executed
1,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:50.806,auditd,Audit: Lowly Suspicious Command executed: /usr...,type=SYSCALL msg=audit(1741273009.274:3880): a...,NaN,NaN,NaN,NaN,head,5.0,command,Command executed
2,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:50.862,auditd,Audit: Lowly Suspicious Command executed: /usr...,type=SYSCALL msg=audit(1741273009.294:3884): a...,NaN,NaN,NaN,NaN,head,5.0,command,Command executed
3,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:50.998,auditd,Audit: Lowly Suspicious Command executed: /usr...,type=SYSCALL msg=audit(1741273009.328:3904): a...,NaN,NaN,NaN,NaN,head,5.0,command,Command executed
4,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:51.053,auditd,Audit: Lowly Suspicious Command executed: /usr...,type=SYSCALL msg=audit(1741273009.346:3908): a...,NaN,NaN,NaN,NaN,head,5.0,command,Command executed

In [8]:
filtered_data.shape

(5167, 14)

In [9]:
filtered_data['Description']=filtered_data['Description'].map({'Audit: Highly Suspicious Command executed: /bin/nc':0,'Audit: Lowly Suspicious Command executed: /usr/bin/head':1})

C:\Users\arnav\AppData\Local\Temp\ipykernel_8768\1808046586.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['Description']=filtered_data['Description'].map({'Audit: Highly Suspicious Command executed: /bin/nc':0,'Audit: Lowly Suspicious Command executed: /usr/bin/head':1})

In [24]:
filtered_data.head()

,Agent_name,User,Timestamp,Decoder_name,Description,Full_log,Command,Level,Activity,Action
0,host-accesible_simulation,camilo,2025-03-06 13:44:07.090,auditd,1,type=SYSCALL msg=audit(1741268643.921:34295): ...,head,5.0,command,Command executed
1,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:50.806,auditd,1,type=SYSCALL msg=audit(1741273009.274:3880): a...,head,5.0,command,Command executed
2,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:50.862,auditd,1,type=SYSCALL msg=audit(1741273009.294:3884): a...,head,5.0,command,Command executed
3,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:50.998,auditd,1,type=SYSCALL msg=audit(1741273009.328:3904): a...,head,5.0,command,Command executed
4,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:51.053,auditd,1,type=SYSCALL msg=audit(1741273009.346:3908): a...,head,5.0,command,Command executed

In [25]:
filtered_data['Content'].isnull().sum()

KeyError: 'Content'

In [ ]:
# Calculate the number of NaN values in 'Content', 'To', and 'From' columns
nan_content = filtered_data['Content'].isnull().sum()
nan_to = filtered_data['To'].isnull().sum()
nan_from = filtered_data['From'].isnull().sum()
print(f"NaN in Content: {nan_content}")
print(f"NaN in To: {nan_to}")
print(f"NaN in From: {nan_from}")

NaN in Content: 5167
NaN in To: 5167
NaN in From: 5167

In [ ]:
filtered_data.head()

,Agent_name,User,Timestamp,Decoder_name,Description,Full_log,Command,Level,Activity,Action
0,host-accesible_simulation,camilo,2025-03-06 13:44:07.090,auditd,1,type=SYSCALL msg=audit(1741268643.921:34295): ...,head,5.0,command,Command executed
1,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:50.806,auditd,1,type=SYSCALL msg=audit(1741273009.274:3880): a...,head,5.0,command,Command executed
2,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:50.862,auditd,1,type=SYSCALL msg=audit(1741273009.294:3884): a...,head,5.0,command,Command executed
3,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:50.998,auditd,1,type=SYSCALL msg=audit(1741273009.328:3904): a...,head,5.0,command,Command executed
4,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:51.053,auditd,1,type=SYSCALL msg=audit(1741273009.346:3908): a...,head,5.0,command,Command executed

In [27]:
filtered_data['Description'].value_counts()

Description
0    3279
1    1888
Name: count, dtype: int64

In [38]:
filtered_data['Level'].value_counts()

Level
12.0    3279
5.0     1888
Name: count, dtype: int64

In [39]:
filtered_data=filtered_data.drop(columns=['Level','Command'])

In [40]:
filtered_data.head()

,Agent_name,User,Timestamp,Decoder_name,Description,Full_log,Activity,Action
0,host-accesible_simulation,camilo,2025-03-06 13:44:07.090,auditd,1,type=SYSCALL msg=audit(1741268643.921:34295): ...,command,Command executed
1,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:50.806,auditd,1,type=SYSCALL msg=audit(1741273009.274:3880): a...,command,Command executed
2,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:50.862,auditd,1,type=SYSCALL msg=audit(1741273009.294:3884): a...,command,Command executed
3,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:50.998,auditd,1,type=SYSCALL msg=audit(1741273009.328:3904): a...,command,Command executed
4,atacante_22cdbe317138f0d8f0137e45f930a42e950d036c,ubuntu,2025-03-06 14:56:51.053,auditd,1,type=SYSCALL msg=audit(1741273009.346:3908): a...,command,Command executed

In [41]:
# Save the filtered data to a CSV file
filtered_data.to_csv('filtered_data.csv', index=False)